### ISSUE TITLE
Randomly generated puzzles with multiple solutions

### ISSUE THREAD

**Issue by pinoaffe** [jaredforrest/nonocross#1]
Hi, first of all: I really love the app and enjoy playing the game.
I encountered one thing: some of the random games have several correct solutions - is this considered a bug, or is this by design?

**Comment by jaredforrest** [comment]
This was originally by design as I didn't think it detracted from play-ability, but I am open to changing this in the future if people want unique puzzles.

**Comment by pinoaffe** [comment]
okay, I was just slightly confused the first couple of times as this makes it different from other nonocross games, I don't think a change is necessary

**Comment by hcgrove** [comment]
I was confused the first couple of times I encountered it. You might consider making it a switch whether people want a puzzle with a unique solution.

**Comment by hcgrove** [comment]
I've played more games, and can now safely say that I prefer games with a unique solution. When there are multiple solutions, I reach a point where I have to ask if the reason I can't get further with logic reasoning is that there are multiple solutions or that I have missed something.

**Comment by jaredforrest** [comment]
I've just pushed an update fixing this which should come to F-droid within the next few weeks

**Comment by Loirooriol** [comment]
I'm curious from an algorithmic point of view. The code seems to find all solutions to ensure there's only one. But this seems kinda expensive, given that in general it's a NP-complete problem. Can you just get way due to the size constraints of the grid?
