### ISSUE TITLE
Dragging fast can skip cells

### ISSUE THREAD

**Issue by Loirooriol** [jaredforrest/nonocross#10]
Open a big grid (e.g. 15x15) and drag along a row or column, moving you finger fast.
Result: some cells are not marked.
Expected: all cells between the start and end cells should be marked.

**Comment by jaredforrest** [comment]
I've fixed this is single line fill mode, should come through in F-Droid in a week or so.

**Comment by Loirooriol** [comment]
Works well, thanks.
