### ISSUE TITLE
Tapping cell may undo instead

### ISSUE THREAD

**Issue by Loirooriol** [jaredforrest/nonocross#11]
This seems a strange bug that I have encountered more than once, but I don't have proper STR.
Just sometimes I tap a cell to mark it, but instead of that, the last action is undone, like when clicking the undo icon. But my fingers are not near the undo icon so it's not possible that I have accidentally fat-fingered it.

**Comment by jaredforrest** [comment]
Hmm, very strange bug, not really sure what could be causing this.

**Comment by jaredforrest** [comment]
I'm closing but if this is still a problem comment and I can reopen
