### ISSUE TITLE
[Feature Request] Cross / Square Toggle

### ISSUE THREAD

**Issue by aaronhatesregex** [jaredforrest/nonocross#2]
It's great to see Nonogram app on F-Droid!

There is a single feature I want desperately -- mark cross on wrong places. I don't know how to call that toggle tbh, but it's available in [PICROSS S4](https://www.nintendo.com/games/detail/picross-s4-switch/) and [Nonogram.com](https://play.google.com/store/apps/details?id=com.easybrain.nonogram) (which is included in Google Play Pass if you happen to be a subscriber). You can see the button in the preview images.

![nonocross](https://user-images.githubusercontent.com/74544956/104172193-c14edd80-53fb-11eb-98cd-f9a9c248fca4.png)

IMO, It's an essential feature for 15*15 or larger nonograms. Sadly I don't know anything about Java / Kotlin so I can't do it myself :(.

**Comment by jaredforrest** [comment]
If you long press it should put a cross in that place, but I can add a toggle if that is easier than a long press. I'll also add a guide/FAQ to the app at some point as this is not documented anywhere currently

**Comment by aaronhatesregex** [comment]
> If you long press it should put a cross in that place

Glad to know that!

> but I can add a toggle if that is easier than a long press

I guess it's more convient and obvious to add a visual toggle than a hidden operation, or better, a option to enable / disable that in a now no-where-to-be-found setting menu.

I'll close this issue anyway since the feature is partially achieved.
