### ISSUE TITLE
BUG: big grid have cell under undo or trashbin buttons

### ISSUE THREAD

**Issue by 1000i100** [jaredforrest/nonocross#21]
If i generate a level with difficulty 10, 15 row and more than 30 line, the last lines will be unreachable because undo and trash are superposed.

**Comment by jaredforrest** [comment]
I can't seem to replicate this, would you mind sending a screenshot along with device details?

**Comment by 1000i100** [comment]
![Screenshot_20210628-131949_Nonocross](https://user-images.githubusercontent.com/2516773/123628816-cec61b80-d813-11eb-8751-348aa185b820.png)
