### ISSUE TITLE
Don't overwrite defined cell when swiping

### ISSUE THREAD

**Issue by 1000i100** [jaredforrest/nonocross#23]
If i click on a defined cell, i can change it (this allready work)

If i click and swipe in a direction, today it change all over the line ignoring what was set previously.
I would like to change this behavior : 
if y swipe from an empty cell, i will add (color or cross) only to empty cells of this line or collumn, but not empty cell wil stay as is.
If y swipe from a defined cell, only those in the same state will be affected.

**Comment by A-Nicoladie** [comment]
It would be nice to have a parameter to determine this behavior (overwrite cells value on swip: on/off)
