### ISSUE TITLE
"Default levels" is misaligned

### ISSUE THREAD

**Issue by Loirooriol** [jaredforrest/nonocross#27]
The other buttons are more or less centered, but "Default levels" is shifted to the left:

![home](https://user-images.githubusercontent.com/7477678/161133713-f84ad72e-8f68-4baa-aeaa-9ffc3814b800.png)

**Comment by mueller-ma** [comment]
In my opinion this is a valid bug report. With the German translation the width of the buttons varies even more.

Maybe remove the background of the buttons or set the `minWidth` attribute?
