### ISSUE TITLE
what should happen after puzzle solved?

### ISSUE THREAD

**Issue by voxspox** [jaredforrest/nonocross#3]
Hi, I filled all fields (I think correctly) but what happens then??

**Comment by jaredforrest** [comment]
Hmm, there should be a popup saying the level is complete.
Would you mind posting a screenshot along with the android version?
![screeen](https://user-images.githubusercontent.com/56826080/105243858-8e2cec80-5b67-11eb-9dd8-b7a3bcadaf20.png)

**Comment by voxspox** [comment]
sorry, can not reproduce the setting. May be later :)
