### ISSUE TITLE
[Feature Request] Add hint or prompt when pressing the Back button when playing a level with progress

### ISSUE THREAD

**Issue by thurstylark** [jaredforrest/nonocross#33]
Currently, if the user is playing a level, and the grid is empty, it takes only one Back button press to return to the menu, but it takes two presses if the grid is non-empty. This is a nice feature to catch accidental presses, but there's no indication to the user that the app is responding to the first Back button press.

I think the simplest solution would be to fire a toast that says something along the lines of "Press Back again to return to the menu".

What I'd like even better is if the first Back button press would launch a "Really return to the menu?" prompt which also specifies that the level and progress will be discarded, and include a "Save Level and return to Menu" button along with the standard yes/no options.

Bonus points for adding preferences that make this behavior optional :)

**Comment by lianergoist** [comment]
+1. I was going to suggest the same. Have lost more than a few games because of this back button...
