### ISSUE TITLE
switch for fill mode

### ISSUE THREAD

**Issue by voxspox** [jaredforrest/nonocross#4]
Currently short press marks a field blue and long press marks red. Long press is for me a bit uncomfortable, especially when marking several fields.

I want to propose a mode switch. The switch changes the short press action between blue and red.

**Comment by jaredforrest** [comment]
This should be simple to add so I'll try to add it asap

**Comment by jaredforrest** [comment]
The update has been pushed through on fdroid, so I'm closing the issue
