### ISSUE TITLE
Blue hints not always shown

### ISSUE THREAD

**Issue by mueller-ma** [jaredforrest/nonocross#43]
As you can see in the screenshot the "2" of the "2 1" isn't blue, but two squares have been selected:

![screenshot](https://user-images.githubusercontent.com/22525368/173135251-e5ccdabb-dd15-4728-91da-f6534dbef4a0.png)

**Comment by jaredforrest** [comment]
This is essentially the same issue as #13 as the blue hints code is currently very simplistic and needs an overhaul at some point

**Comment by mueller-ma** [comment]
Closing as duplicate of #13.
