### ISSUE TITLE
Blue hints not cleared when resetting level

### ISSUE THREAD

**Issue by mueller-ma** [jaredforrest/nonocross#46]
Steps to reproduce:

- Open a level 
- Fill some squares
- Press dustbin icon

Expected: All blue hints are gone, because no square is filled anymore.
Actual: Blue hints are still shown

**Comment by Loirooriol** [comment]
Blue hints are not recalculated either when clicking the undo button.

**Comment by mueller-ma** [comment]
Fixed by [1.3.3](https://github.com/jaredforrest/nonocross/releases/tag/1.3.3)
