### ISSUE TITLE
Why the camera permission?

### ISSUE THREAD

**Issue by mmahmoudian** [jaredforrest/nonocross#58]
I was wondering why such game would need camera permission? It would be nice to have a clear explanation on README and on F-droid:

![Screenshot_20220902-010318~2.png](https://user-images.githubusercontent.com/390889/188020869-057bd870-64ef-40e8-87a7-7a84e82ae5c6.png)

**Comment by airon90** [comment]
I suppose that permission is needed in order to import levels via QR code

**Comment by jaredforrest** [comment]
Yes it's to import levels by QR code. I've added a note to the README and on F-droid.
