### ISSUE TITLE
Some translations variable not working in strings.xml

### ISSUE THREAD

**Issue by joyel24** [jaredforrest/nonocross#60]
I found some translations variable that are not working in strings.xml, here is what I found : 

```
<string name="confirm_exit">Are you sure you want to exit?</string>
<string name="lose_unsaved_data">Any unsaved data will be lost.</string>
<string name="save">Save</string>
<string name="not_save">Don\'t save</string>
```

**Comment by jaredforrest** [comment]
I've just pushed a change, it might fix this issue.

**Comment by joyel24** [comment]
> I've just pushed a change, it might fix this issue.

Just tested and appears to work now ! Congratulation 👌
