### ISSUE TITLE
Provide more feedback when placing a cross

### ISSUE THREAD

**Issue by hcgrove** [jaredforrest/nonocross#7]
When I perform a long press on a tile to set a cross, my finger obscures the tile, so I can't see if a cross is set, and experience has shown that I don't always press long enough and end up marking the tile instead of setting a cross, some sort of feedback (my suggestion is a small vibration = haptic feedback) would help me know when my press is long enough.

**Comment by jaredforrest** [comment]
I had a bit of trouble getting vibrations working earlier but I'll have another try next time I look at the app

**Comment by jaredforrest** [comment]
I have updated the app with an option to vibrate on placing a cross.
