### ISSUE TITLE
Add 'Undo' button

### ISSUE THREAD

**Issue by BWPanda** [jaredforrest/nonocross#8]
Sometimes I think I may have marked the wrong square(s) by mistake (fat fingers, small squares), but then I'm not sure which are wrong and which I marked (correctly) previously.

An 'undo' button would be very handy in these situations. And maybe a 'redo' button too...

**Comment by jaredforrest** [comment]
That would require a bit of overhead (i.e. remembering the game state after every move), but is definitely a useful feature, I'll try and sort something out when I've got a bit more time.

**Comment by jaredforrest** [comment]
I have updated with an undo button
