### ISSUE TITLE
More Material Design 3 updates

### ISSUE THREAD

**Issue by mueller-ma** [jaredforrest/nonocross#88]
There are a few things that could be changed to be more MD3 compliant:

- [x] Use sliders in the random level dialog instead of the deprecated NumberPicker
- [x] Use rounded corners in remaining dialogs
- [ ] Use rounded corners for the filled cells

@jaredforrest Does this sound good for you?

**Comment by jaredforrest** [comment]
The first two sound good buy I'm not sure about rounded corners for the filled cells.
