### ISSUE TITLE
Restrict dragging to current row/column

### ISSUE THREAD

**Issue by BWPanda** [jaredforrest/nonocross#9]
Currently you can drag your finger around to mark multiple squares. This is useful when you know that all squares in a row or column are either filled or blank, but often your finger travels outside that row/column and you mark the wrong squares.

I've filed a separate issue for adding an undo button that will help here, but another option is to restrict dragging to the current row/column.

**Comment by jaredforrest** [comment]
Yes that makes sense, I'll try to implement that in the next update

**Comment by jaredforrest** [comment]
There is now an option (enabled by default) to restrict dragging to one row/column
