### ISSUE TITLE
Wrong buttons in GridView are shown

### ISSUE THREAD

**Issue by mueller-ma** [jaredforrest/nonocross#99]
Some buttons are hidden in some cases, e.g. the "reset zoom" button when zooming is disabled. When pressing the QR code button and then the grid button, all buttons (including the previously hidden ones) are shown.

**Comment by jaredforrest** [comment]
Should be fixed now by 0dfa5a1e6e6561c81274d445b7a9f1551d2321db

**Comment by mueller-ma** [comment]
After saving a level the save button disappears. Toggling the qr code brings it back as well.

Maybe use a dialog for the qr code to avoid all this hide/show logic?
